name: Apprenticeship Exercise Github Actions
run-name: $${{ github.actor }} is running Github Actions.
on:
  push:
    branches: ["main", "github_actions"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # ref: https://github.com/Breachico/Liatrio-Apprenticeship-Exercise/new/main?filename=.github%2Fworkflows%2Fdocker-image.yml&workflow_template=ci%2Fdocker-image

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag go-hello:test

      - name: Build From Image
        run: docker run -d -p 80:80 go-hello:test
 
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master

#      - name: Run Docker Image
#        run: docker run -p 80:3000 go-hello:latest

#  Publish:
 #   needs: build
  #  runs-on: ubuntu-latest
  
#      - name: Deploy
      





