name: Apprenticeship Exercise Github Actions
run-name: $${{ github.actor }} is running Github Actions.
on:
  push:
    branches: ["main", "github_actions", "dockerhub_publish"]

env:
  TAG: ${{github.run_number}}.${{github.sha}} # Decided on with ChatGPT Assistance

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Bulding
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag go-hello:$TAG
      
      # Testing
      - name: Build From Image
        run: docker run -d -p 80:8080 go-hello:$TAG
 
      - name: run tests
        uses: Breachico/github-actions-Liatrio/apprentice-action@master

  publishing: # ref: https://github.com/marketplace/actions/build-and-push-docker-images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Logging Into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: breachico/go-hello:$TAG
      


 #   needs: build
  #  runs-on: ubuntu-latest
  
#      - name: Deploy
      





